### ISSUE TITLE
09.11.18

### ISSUE THREAD

**Issue by bakerqc** [jraeglasgow/Quinn-Jess#4]
Quick Off The Top Of My Head Topics
- Still on inbound line
- Holiday Work Week
- Vegas Flight for Money 20/20
- Review Close but no cigar emails

**Comment by jraeglasgow** [comment]
Homework : -
- Didn't get to five calls a day last week. Need to try and do ten by EOD Friday.
- Will slack emails when he needs help and Jess can write back what to say and talk about later.
